#!/usr/bin/env python3
"""Turn a picture into board/samsung/a145f-splash.h (256-colour palette + RLE).

  python3 tools/samsung-a145f/make_splash.py tools/samsung-a145f/splash/witch-cat.png

The picture should have a black background (the framebuffer is black). It is
cropped to the non-black area, near-black noise (JPEG ringing) is flattened to
pure black, and the result is stored as run-length pairs of (count, palette
index), so a flat-coloured drawing costs a few hundred KiB at most.
Needs Pillow:  pip install pillow   (only to regenerate; the header is committed)
"""
import argparse, os, sys
from PIL import Image

ap = argparse.ArgumentParser()
ap.add_argument("image")
ap.add_argument("-o", "--out", default=os.path.join(
    os.path.dirname(__file__), "..", "..", "board", "samsung", "a145f-splash.h"))
ap.add_argument("--max-width", type=int, default=1000, help="scale down if wider (screen is 1080)")
ap.add_argument("--black", type=int, default=24, help="channels below this become pure black")
a = ap.parse_args()

im = Image.open(a.image).convert("RGB")
px = im.load()
W, H = im.size
for y in range(H):
    for x in range(W):
        r, g, b = px[x, y]
        if max(r, g, b) < a.black:
            px[x, y] = (0, 0, 0)
bbox = im.point(lambda v: 255 if v else 0).convert("L").getbbox()
if not bbox:
    sys.exit("error: picture is all black")
pad = 8
bbox = (max(0, bbox[0] - pad), max(0, bbox[1] - pad), min(W, bbox[2] + pad), min(H, bbox[3] + pad))
im = im.crop(bbox)
if im.width > a.max_width:
    im = im.resize((a.max_width, round(im.height * a.max_width / im.width)), Image.LANCZOS)
w, h = im.size
q = im.quantize(colors=256, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
pal = q.getpalette()[:768]
pal += [0] * (768 - len(pal))
# make sure pure black is palette entry 0 so empty areas are exact
idx = list(q.get_flattened_data()) if hasattr(q, "get_flattened_data") else list(q.getdata())
black = next((i for i in range(256) if pal[3*i:3*i+3] == [0, 0, 0]), None)
if black is None:
    black = min(range(256), key=lambda i: sum(pal[3*i:3*i+3]))
    pal[3*black:3*black+3] = [0, 0, 0]
rle = bytearray()
i, n = 0, len(idx)
while i < n:
    v, j = idx[i], i
    while j < n and idx[j] == v and j - i < 255:
        j += 1
    rle += bytes((j - i, v))
    i = j
words = [(0xFF << 24) | (pal[3*k] << 16) | (pal[3*k+1] << 8) | pal[3*k+2] for k in range(256)]

with open(a.out, "w") as f:
    f.write("/* SPDX-License-Identifier: GPL-2.0 */\n"
            "/* Generated by tools/samsung-a145f/make_splash.py from %s. Do not edit. */\n"
            "#ifndef A145F_SPLASH_H\n#define A145F_SPLASH_H\n\n"
            "#define A145F_SPLASH_WIDTH %d\n#define A145F_SPLASH_HEIGHT %d\n"
            "#define A145F_SPLASH_RLE_LEN %d\n\n" % (os.path.basename(a.image), w, h, len(rle)))
    f.write("/* 0xAARRGGBB, entry 0 or the darkest entry is pure black */\n"
            "static const unsigned int a145f_splash_pal[256] = {\n")
    for k in range(0, 256, 8):
        f.write("\t" + ", ".join("0x%08x" % x for x in words[k:k+8]) + ",\n")
    f.write("};\n\n/* (count, palette index) pairs, row-major */\n"
            "static const unsigned char a145f_splash_rle[] = {\n")
    for k in range(0, len(rle), 24):
        f.write("\t" + ", ".join("%d" % x for x in rle[k:k+24]) + ",\n")
    f.write("};\n\n#endif\n")
print("splash %dx%d, %d RLE bytes -> %s" % (w, h, len(rle), os.path.relpath(a.out)))
